* evil-mark-replace
Replace symbol at point in buffer or function.

[[https://github.com/emacs-evil/evil][EVIL]] is required.
* Install
Place =evil-mark-replace.el= somewhere (say ~/.emacs/lisp), add below code into =~/.emacs=:

#+begin_src elisp
(add-to-list 'load-path "~/.emacs.d/lisp/")
(require 'evil-mark-replace)
#+end_src

* Usage
Here are the commands you can use. Feel free to assign key bindings to them.
** evilmr-replace-in-buffer
Replace in current buffer.
** evilmr-replace-in-defun
Narrow to current function and replace.

* Bug Report
See [[https://github.com/redguardtoo/evil-mark-replace]].

* License
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see [[http://www.gnu.org/licenses/]].
